---
- name: Enable i386 arch
  ansible.builtin.lineinfile: 
    dest: /var/lib/dpkg/arch
    line: i386 
    create: yes
  register: pdkg_config

- name: Install libc6:i386
  ansible.builtin.apt:
    name: libc6:i386
    update_cache: "{{ pdkg_config.changed }}"

- name: Download NVidia driver
  ansible.builtin.get_url:
    url: "{{ nvidia_driver_url }}"
    dest: /root/NVIDIA-Linux-x86_64.run
    mode: '0755'
  register: nvidia_driver_package

- name: Install NVidia driver
  ansible.builtin.command: /root/NVIDIA-Linux-x86_64.run -s --no-kernel-module
  when: nvidia_driver_package is changed
  register: nvidia_driver

- name: Reboot container
  ansible.builtin.reboot:
  when: nvidia_driver is changed
