---
- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Copy config
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0755'
  notify:
    - Restart nginx service

- name: Enable nginx service
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: nginx
    state: started
    enabled: true
