---
version: "3.8"

services:
  localai:
    container_name: localai
    restart: unless-stopped
    image: quay.io/go-skynet/local-ai:latest-aio-gpu-nvidia-cuda-12
    ports:
      - 8080:8080
    environment:
      - DEBUG=true
      - MODELS_PATH=/localai/models
      - THREADS=1 
      - MODELS='github:skynet-go/model-gallery/llama2-7b-chat-gguf.yaml,github:skynet-go/model-gallery/vicuna.yaml'
    volumes:
      - /localai:/localai
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
