---
version: "3.8"

services:
  localai:
    container_name: localai
    restart: unless-stopped
    image: quay.io/go-skynet/local-ai:latest-aio-gpu-nvidia-cuda-12
    ports:
      - 8080:8080
    environment:
      - DEBUG=true
      - MODELS_PATH=/localai/models
      - THREADS=1 
      - 'PRELOAD_MODELS=[{"url": "github:go-skynet/model-gallery/llama2-7b-chat-gguf.yaml", "name": "llama2-7b-chat-gguf"},{"url": "github:go-skynet/model-gallery/vicuna.yaml", "name": "vicuna"}]'
    volumes:
      - /localai:/localai
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
