---
terraform:
  vmid: 1
  hostname: pihole
  ip_address: 10.20.1.1/16
  nameserver: 10.20.0.1
  cpu_core_count: 4
  memory: 4096
  swap: 512
  start_on_boot: true
  rootfs_size: 20G

ansible:
  roles:
    - base
    - pihole
