---
terraform:
  vmid: 110
  hostname: nginx
  ip_address: 10.20.1.10/16
  nameserver: 10.20.0.1
  cpu_core_count: 4
  memory: 4096
  swap: 512
  start_on_boot: true
  rootfs_size: 20G

ansible:
  roles:
    - base
    - nginx_reverse_proxy
