---
terraform:
  vmid: 202
  hostname: ntfy
  ip_address: 10.20.1.202/16
  nameserver: 10.20.0.1
  cpu_core_count: 4
  memory: 2048
  swap: 512
  start_on_boot: true
  rootfs_size: 20G

ansible:
  roles:
    - base
    - ntfy
