---
terraform:
  vmid: 203
  hostname: fileserver
  ip_address: 10.20.1.203/16
  nameserver: 10.20.0.1
  cpu_core_count: 4
  memory: 2048
  swap: 512
  start_on_boot: true
  rootfs_size: 20G

pve_extra:
  - mp0: /zpool/share,mp=/mnt/share,backup=0

ansible:
  roles:
    - base
    - cockpit
