---
terraform:
  vmid: 204
  hostname: jellyfin
  ip_address: 10.20.1.204/16
  nameserver: 10.20.0.1
  cpu_core_count: 6
  memory: 4096
  swap: 1024
  start_on_boot: true
  rootfs_size: 200G
  unprivileged: false

pve_extra:
  - mp0: /zpool/share/movies,mp=/mnt/movies,backup=0
  - mp1: /zpool/share/shows,mp=/mnt/shows,backup=0
  - lxc.cgroup2.devices.allow: c 195:* rwm
  - lxc.cgroup2.devices.allow: c 234:* rwm
  - lxc.cgroup2.devices.allow: c 238:* rwm
  - lxc.mount.entry: /dev/nvidia0 dev/nvidia0 none bind,optional,create=file
  - lxc.mount.entry: /dev/nvidiactl dev/nvidiactl none bind,optional,create=file
  - lxc.mount.entry: /dev/nvidia-uvm dev/nvidia-uvm none bind,optional,create=file
  - lxc.mount.entry: /dev/nvidia-uvm-tools dev/nvidia-uvm-tools none bind,optional,create=file
  - lxc.mount.entry: /dev/nvidia-uvm-tools dev/nvidia-caps/nvidia-cap1 none bind,optional,create=file
  - lxc.mount.entry: /dev/nvidia-uvm-tools dev/nvidia-caps/nvidia-cap2 none bind,optional,create=file

ansible:
  roles:
    - base
    - gpu_drivers
    - jellyfin
