---
terraform:
  vmid: 205
  hostname: dockerhost
  ip_address: 10.20.1.205/16
  nameserver: 10.20.0.1
  cpu_core_count: 12
  memory: 12288
  swap: 2048
  start_on_boot: true
  rootfs_size: 200G

pve_extra:
  - lxc.cgroup.devices.allow: c 10:200 rwm
  - lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file
  - mp0: /zpool/share,mp=/pve/share,backup=0

ansible:
  roles:
    - base
    - docker
    - role: containers
      vars:
        containers:
          - name: portainer
            state: up
          - name: uptime-kuma
            state: up
          - name: homarr
            state: up
          - name: arrs
            state: up
          - name: actualbudget
            state: up
