---
terraform:
  vmid: 206
  hostname: homeassistant
  ip_address: 10.20.1.206/16
  nameserver: 10.20.0.1
  cpu_core_count: 4
  memory: 4096
  swap: 512
  start_on_boot: true
  rootfs_size: 50G

pve_extra:
  - mp0: /zpool/homeassistant,mp=/mnt/homeassistant,backup=0

ansible:
  roles:
    - base
    - docker
<<<<<<< feat/lint
    - homeassistant
=======
    - role: containers
      vars:
        containers:
          - name: homeassistant
            state: up
>>>>>>> main
