---
terraform:
  vmid: 207
  hostname: localai
  ip_address: 10.20.1.207/16
  nameserver: 10.20.0.1
  cpu_core_count: 12
  memory: 12288
  swap: 2048
  start_on_boot: true
  rootfs_size: 500G


ansible:
  roles:
    - base
    - docker
    - role: containers
      vars:
        containers:
          - name: openwebui
            state: up
          - name: litellm
            state: up      
