---
terraform:
  vmid: 209
  hostname: signumminer
  ip_address: 10.20.1.209/16
  nameserver: 10.20.0.1
  cpu_core_count: 32
  memory: 8192
  swap: 2048
  start_on_boot: true
  rootfs_size: 100G

pve_extra:
  - mp0: /mnt/pve/Plot0/plots,mp=/mnt/plots0,backup=0
  - mp1: /mnt/pve/Plot1/plots,mp=/mnt/plots1,backup=0
  - mp2: /mnt/pve/Plot2/plots,mp=/mnt/plots2,backup=0

ansible:
  roles:
    - base
    - role: signum_miner
      vars:
        signum_miner_plot_dirs:
          - /mnt/plots0
          - /mnt/plots1
          - /mnt/plots2
