---
terraform:
  vmid: 217
  hostname: hermes
  ip_address: 10.20.1.217/16
  nameserver: 10.20.0.1
  cpu_core_count: 4
  memory: 8192
  swap: 1024
  start_on_boot: true
  rootfs_size: 30G
  extra_networks:
    - bridge: vmbr2
      tag: 1
      ip: 192.168.250.217/16
    - bridge: vmbr2
      tag: 10
      ip: 10.10.250.217/16
    - bridge: vmbr2
      tag: 50
      ip: 10.50.250.217/16

pve_extra:
  - mp0: /zpool/hermes,mp=/mnt/hermes,backup=0

ansible:
  roles:
    - base
    - docker
    - hermes_agent
