---
terraform:
  vmid: 502
  hostname: forge-runner-2
  ip_address: 10.20.5.3/16
  nameserver: 10.20.0.1
  cpu_core_count: 4
  memory: 4096
  swap: 1024
  start_on_boot: true
  rootfs_size: 40G

ansible:
  roles:
    - base
    - docker
    - role: forgejo_runner
      vars:
        forgejo_runner_uuid_env: FORGEJO_RUNNER_502_UUID
        forgejo_runner_secret_env: FORGEJO_RUNNER_502_SECRET
