---
terraform:
  vmid: 502
  hostname: github-worker-2
  ip_address: 10.20.5.2/16
  nameserver: 10.20.0.1
  cpu_core_count: 4
  memory: 2048
  swap: 512
  start_on_boot: true
  rootfs_size: 20G
  mount_points:
    - storage: /zpool/terraform
      mp: /pve/terraform
      size: 1G

ansible:
  roles:
    - base
    - role: github_worker
