---
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - GENERIC_TIMEZONE="Europe/London"
      - TZ="Europe/London"
      - N8N_HOST=n8n.homelab.matagoth.com
      - N8N_PROTOCOL=https
    volumes:
      - n8n:/home/node/.n8n


volumes:
  n8n:
