---
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - GENERIC_TIMEZONE="Europe/Berlin"
      - TZ="Europe/Berlin"
    volumes:
      - n8n:/home/node/.n8n


volumes:
  n8n:
