global:
  scrape_interval: 60s
  evaluation_interval: 60s
  scrape_timeout: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: prometheus
