global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: prometheus
  - job_name: proxmox
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["localhost:9108"]
        labels:
          app: proxmox
  - job_name: graphana
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["localhost:3000"]
        labels:
          app: graphana
