---
# PLEASE ONLY ENTER YOUR PASSPHRASE BELOW IF YOU ARE GOING TO MINE SOLO!
# YOU DO NOT NEED TO ENTER YOUR PASSPHRASE FOR POOL MINING.
# NEVER POST YOUR CONFIG.YAML INCLUDING YOUR PASSPHRASE TO ANY BOARD OR CHAT!
# account_id_to_secret_phrase:          # define accounts and passphrases for solo mining 


# List of directories with your plot files, adjust to suit your disks
plot_dirs:
{% for dir in signum_miner_plot_dirs %}
 - '{{ dir }}'
{% endfor %}

url: 'https://pool.signumcoin.ro'      # mainnet pool
#url: 'http://nivbox.co.uk:9000'      # testnet pool
#url: 'http://localhost:8125'         # solo mining
#url: 'http://localhost:8125'         # solo mining testnet
#url: 'http://localhost:6876'         # solo mining testnet

hdd_reader_thread_count: 0            # default 0 (=auto: number of disks)
hdd_use_direct_io: true               # default true
hdd_wakeup_after: 240                 # default 240s

cpu_threads: 0                        # default 0 (=auto: number of logical cpu cores)
cpu_worker_task_count: 16             # default 4 (0=GPU only)
cpu_nonces_per_cache: 65536           # default 65536
cpu_thread_pinning: false             # default false

gpu_threads: 0                        # default 0 (=GPU off)
gpu_platform: 0                       # default 0
gpu_device: 0                         # default 0
gpu_worker_task_count: 0              # default 0 (=CPU only)
gpu_nonces_per_cache: 262144          # default 262144
gpu_mem_mapping: false                # default false
gpu_async: false                      # default false

target_deadline: 31536000             # default 31536000 (1 year)
# account_id_to_target_deadline:        # target dls for multi-id (optional)
#  10282355196851764065: 600000
#  1796535821016683299: 55555555

get_mining_info_interval: 3000        # default 3000ms
timeout: 5000                         # default 5000ms
send_proxy_details: true              # default false
submit_only_best: true                # default true
#additional_headers:                  # add/overwrite html header
#  "AccountKey" : "1234567890"

console_log_level: 'info'             # default Info, options (off, error, warn, info, debug, trace)
logfile_log_level: 'info'             # default Warn, options (off, error, warn, info, debug, trace)
logfile_max_count: 10                 # maximum number of log files to keep
logfile_max_size : 20                 # maximum size per logfile in MiB

show_progress: true                   # default true  
show_drive_stats: false               # default false 
benchmark_only: 'disabled'            # default disabled, options (disabled, I/O, XPU)

# Low noise log patterns
console_log_pattern: "{({d(%H:%M:%S)} [{l}]):16.16} {m}{n}"
logfile_log_pattern: "{({d(%Y-%m-%d %H:%M:%S)} [{l}]):26.26} {m}{n}"

# More detailed log patterns
#console_log_pattern: "{d(%H:%M:%S.%3f%z)} [{h({l}):<5}] [{T}] [{t}] - {M}:{m}{n}"
#logfile_log_pattern: "{d(%Y-%m-%dT%H:%M:%S.%3f%z)} [{h({l}):<5}] [{T}]-[{t}] [{f}:{L}] - {M}:{m}{n}"
