---
mappings:
  - match: proxmox.lxc.*.*
    name: 'proxmox_lxc_${2}'
    labels:
      vmid: ${1}

  - match: proxmox.nodes.*.*.*
    name: 'proxmox_node_${2}_${3}'
    labels:
      node_name: ${1}

  - match: proxmox.qemu.*.*
    name: proxmox_qemu_${2}
    labels:
      vmid: ${1}

  - match: proxmox.storages.*.*.*
    name: proxmox_storage_${3}
    labels:
      node_name: ${1}
      storage_name: ${2}

  - match: proxmox.nodes.*.nics.*.*
    name: 'proxmox_node_nic_${3}'
    labels:
      node_name: ${1}
      nic: ${2}
