---
- name: Get github-runner latest version
  ansible.builtin.uri:
    url: https://api.github.com/repos/actions/runner/releases/latest
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: runner_version

- name: Debug
  ansible.builtin.debug:
    msg: "https://github.com/actions/runner/releases/download/{{ runner_version.json.tag_name }}/actions-runner-linux-x64-{{ runner_version.json.tag_name | replace('v', '') }}.tar.gz"
