---
- name: Allow root apt sandbox
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/10sandbox
    line: 'APT::Sandbox::User "root";'

- name: Install Dependencies
  ansible.builtin.apt:
    update_cache: yes
    name:
      - apparmor
      - cifs-utils
      - dbus
      - jq
      - libglib2.0-bin
      - lsb-release
      - network-manager
      - nfs-common
      - systemd-journal-remote
      - systemd-resolved
      - udisks2
    state: present

- name: Install HomeAssistant OS Agent
  ansible.builtin.apt:
    deb: "https://github.com/home-assistant/os-agent/releases/download/{{ homeassistant_agent_version }}/os-agent_{{ homeassistant_agent_version }}_linux_x86_64.deb"

- name: Install HomeAssistant Supervised
  ansible.builtin.apt:
    deb: "https://github.com/home-assistant/supervised-installer/releases/download/{{ homeassistant_supervised_version }}/homeassistant-supervised.deb"
