#!/usr/bin/env python3
"""
This script generates an Ansible playbook for configuring an external host.

Usage:
  ./render_external_host_playbook <hostname>

Arguments:
  hostname: The hostname of the external host (file name under
            config/external-hosts/, without the .yml suffix).

The script performs the following steps:
1. Reads the external-host configuration from
   './config/external-hosts/<hostname>.yml'.
2. Extracts the target IP, Ansible roles, and Ansible tasks.
3. Constructs an Ansible playbook targeting the host's IP.
4. Outputs the final playbook to stdout in YAML format.

Dependencies:
  - ruamel.yaml: A YAML parser/emitter that supports round-trip preservation.

Example:
  ./render_external_host_playbook pi-01
"""


import sys
import ruamel.yaml as yaml

hostname = sys.argv[1]

conf_path = f'./config/external-hosts/{hostname}.yml'
with open(conf_path) as conf_file:
  conf = yaml.YAML().load(conf_file)

host_ip = conf['identity']['ip']
ansible_roles = conf['ansible'].get('roles')
ansible_tasks = conf['ansible'].get('tasks')

playbook = {
  'name': f'External host {hostname}',
  'hosts': host_ip
}

if ansible_roles:
  playbook.update({'roles': ansible_roles})

if ansible_tasks:
  playbook.update({'tasks': ansible_tasks})

yaml.YAML().dump([playbook], sys.stdout)
