---
- name: Template files (explicitly skip directories in order to use the 'src' attribute)
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: "/containers/{{ container.name }}/{{ item.path }}"
    mode: '{{ item.mode }}'
  with_community.general.filetree: "../../../config/docker/{{ container.name }}/"
  when: item.state == "file" and container.state == "up"
