---
- name: Copy config
  ansible.builtin.copy:
    src: "../../../config/docker/{{ item }}/"
    dest: "/containers/{{ item }}/"
  register: config
  loop: "{{ containers }}"

- name: Restart container
  ansible.builtin.command: "docker compose up -d -f /containers/{{ item.item }}/docker-compose.yaml"
  when: item is changed
  loop: "{{ config.results }}"
