---
- name: Copy files
  include_tasks: copy_files.yaml
  loop: "{{ containers }}"
  loop_control:
    loop_var: container

- name: Stop container
  ansible.builtin.command: "docker compose -f /containers/{{ item.name }}/docker-compose.yaml down"
  when: item.state != "up"
  loop: "{{ containers }}"

- name: Remove container config
  ansible.builtin.file:
    path: /etc/foo
    state: absent
  when: item.state == "destroyed"
  loop: "{{ containers }}"

- name: Prune and update images
  include_tasks: update_and_clear_images.yaml

- name: Restart container
  ansible.builtin.command: "docker compose -f /containers/{{ item.name }}/docker-compose.yaml up -d"
  when: item.state == "up"
  loop: "{{ containers }}"
