---
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP={{ lookup('ansible.builtin.env', 'VPN_ENDPOINT_IP_IRELAND') }}
      - VPN_ENDPOINT_PORT={{ lookup('ansible.builtin.env', 'VPN_ENDPOINT_PORT_IRELAND') }}
      - WIREGUARD_PUBLIC_KEY={{ lookup('ansible.builtin.env', 'WIREGUARD_PUBLIC_KEY_IRELAND') }}
      - WIREGUARD_PRIVATE_KEY={{ lookup('ansible.builtin.env', 'WIREGUARD_PRIVATE_KEY_IRELAND') }}
      - WIREGUARD_ADDRESSES={{ lookup('ansible.builtin.env', 'WIREGUARD_ADDRESSES_IRELAND') }}
    ports:
      - 9696:9696       # prowlarr
      - 8989:8989       # sonarr
      - 7878:7878       # radarr
      - 8888:8888       # qbittorrent
      - 6881:6881       # qbittorrent
      - 6881:6881/udp   # qbittorrent
    networks:
      gluetun_network:
        ipv4_address: 10.5.0.10

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/London
    ports:
      - 8191:8191
    restart: unless-stopped
    network_mode: service:gluetun

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - TZ=Etc/UTC
    volumes:
      - prowlarr_data:/config
    restart: unless-stopped
    network_mode: service:gluetun

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sonarr_data:/config
      - /pve/share/shows:/tv
      - /pve/share/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - radarr_data:/config
      - /pve/share/movies:/movies
      - /pve/share/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8888
    volumes:
      - qbittorrent_data:/config
      - /pve/share/downloads:/downloads
      - /pve/share/404:/404
    restart: unless-stopped
    network_mode: service:gluetun

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sabnzbd_data:/config
      - /pve/share/downloads:/downloads
      - /pve/share/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      gluetun_network:
        ipv4_address: 10.5.0.5


volumes:
  prowlarr_data:
  sonarr_data:
  radarr_data:
  qbittorrent_data:
  sabnzbd_data:

networks:
  gluetun_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
