---
version: "3.8"

services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:v3.36.0
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP={{ lookup('ansible.builtin.env', 'VPN_ENDPOINT_IP_IRELAND') }}
      - VPN_ENDPOINT_PORT={{ lookup('ansible.builtin.env', 'VPN_ENDPOINT_PORT_IRELAND') }}
      - WIREGUARD_PUBLIC_KEY={{ lookup('ansible.builtin.env', 'WIREGUARD_PUBLIC_KEY_IRELAND') }}
      - WIREGUARD_PRIVATE_KEY={{ lookup('ansible.builtin.env', 'WIREGUARD_PRIVATE_KEY_IRELAND') }}
      - WIREGUARD_ADDRESSES={{ lookup('ansible.builtin.env', 'WIREGUARD_ADDRESSES_IRELAND') }}
    ports:
      - 9696:9696  # prowlarr

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.10.5
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - prowlarr_data:/config
    restart: unless-stopped
    network_mode: service:gluetun

volumes:
  prowlarr_data:
