---
version: "3.8"

services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:v3.36.0
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=37.120.198.162
      - VPN_ENDPOINT_PORT=1443
      - WIREGUARD_PUBLIC_KEY=3ZpSpiWuyN2+Qn786t+ejcNul6Tq5b6+9uB6sGSLHhc=
      - WIREGUARD_PRIVATE_KEY={{ lookup('ansible.builtin.env', 'WIREGUARD_PRIVATE_KEY') }}
      # - WIREGUARD_PRESHARED_KEY=xOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      - WIREGUARD_ADDRESSES=10.13.122.21/24
    ports:
      - 9696:9696  # prowlarr

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.10.5
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - prowlarr_data:/config
    restart: unless-stopped
    network_mode: service:gluetun

volumes:
  prowlarr_data:
