---
- name: Eanble i386 arch
  ansible.builtin.lineinfile: 
    dest: /var/lib/dpkg/arch
    line: i386 
    create: yes
  register: pdkg_config

- name: Install libc6:i386
  ansible.builtin.apt:
    name: libc6:i386
    update_cache: "{{ pdkg_config.changed }}"

- name: Download NVidia driver
  ansible.builtin.get_url:
    url: "{{ nvidia_driver_url }}"
    dest: /tmp/NVIDIA-Linux-x86_64.run
    mode: '0755'
  register: nvidia_driver_package

- name: Install NVidia driver
  ansible.builtin.command: /tmp/NVIDIA-Linux-x86_64.run --no-questions
  when: nvidia_driver_package is changed
  register: nvidia_driver

- name: Reboot container
  ansible.builtin.reboot:
  when: nvidia_driver is changed

- name: Install jellyfin-ffmpeg
  ansible.builtin.apt:
    deb: "https://repo.jellyfin.org/releases/server/debian/versions/jellyfin-ffmpeg/{{ jellyfin_ffmpeg_version }}/jellyfin-ffmpeg{{ jellyfin_ffmpeg_version[0] }}_{{ jellyfin_ffmpeg_version }}-bookworm_amd64.deb"
  notify: 
    - Restart Jellyfin

- name: Install jellyfin-server
  ansible.builtin.apt:
    deb: "https://repo.jellyfin.org/releases/server/debian/versions/stable/server/{{ jellyfin_server_version }}/jellyfin-server_{{ jellyfin_server_version }}-1_amd64.deb"
  notify: 
    - Restart Jellyfin

- name: Install jellyfin-web
  ansible.builtin.apt:
    deb: "https://repo.jellyfin.org/releases/server/debian/versions/stable/web/{{ jellyfin_web_version }}/jellyfin-web_{{ jellyfin_web_version }}-1_all.deb"
  notify: 
    - Restart Jellyfin

- name: Enable Jellyfin service
  ansible.builtin.service:
    name: jellyfin
    enabled: true
    state: started

