---
- name: Install jellyfin-ffmpeg
  ansible.builtin.apt:
    deb: "{{ jellyfin_ffmpeg_package_url }}"
  notify: 
    - Restart Jellyfin

- name: Install jellyfin-server
  ansible.builtin.apt:
    deb: "{{ jellyfin_server_package_url }}"
  notify: 
    - Restart Jellyfin

- name: Install jellyfin-web
  ansible.builtin.apt:
    deb: "{{ jellyfin_web_package_url }}"
  notify: 
    - Restart Jellyfin

- name: Enable Jellyfin service
  ansible.builtin.service:
    name: jellyfin
    enabled: true
    state: started
