---
# - name: Install software-properties-common
#   ansible.builtin.apt:
#     name: software-properties-common

# - name: Add Universe repo
#   ansible.builtin.command: add-apt-repository universe

# - name: APT cache update
#   ansible.builtin.apt_repository:
#     update_cache: true

- name: Install jellyfin-ffmpeg
  ansible.builtin.apt:
    deb: "https://repo.jellyfin.org/releases/server/debian/versions/jellyfin-ffmpeg/{{ jellyfin_ffmpeg_version }}/jellyfin-ffmpeg{{ jellyfin_ffmpeg_version[0] }}_{{ jellyfin_ffmpeg_version }}-bookworm_amd64.deb"

- name: Install jellyfin-server
  ansible.builtin.apt:
    deb: "https://repo.jellyfin.org/releases/server/debian/versions/stable/server/{{ jellyfin_server_version }}/jellyfin-server_{{ jellyfin_server_version }}-1_amd64.deb"

- name: Install jellyfin-web
  ansible.builtin.apt:
    deb: "https://repo.jellyfin.org/releases/server/debian/versions/stable/web/{{ jellyfin_web_version }}/jellyfin-web_{{ jellyfin_web_version }}-1_all.deb"


