---
- name: Create LocalAI directory
  ansible.builtin.file:
    path: /localai/models
    state: directory

- name: Deploy compose file
  ansible.builtin.copy:
    src: docker-compose.yaml
    dest: /localai/docker-compose.yaml

- name: Restart LocalAI
  ansible.builtin.command: docker compose -f /localai/docker-compose.yaml up -d
