- name: Keyrings folder
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory

- name: Instal gpg
  ansible.builtin.apt:
    name: gpg
    state: present

- name: Ntfy.sh gpg key
  ansible.builtin.apt_key:
    url: https://archive.heckel.io/apt/pubkey.txt
    keyring: /etc/apt/keyrings/archive.heckel.io.gpg

- name: Instal apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Heckel repo
  ansible.builtin.copy:
    src: archive.heckel.io.list
    dest: /etc/apt/sources.list.d/archive.heckel.io.list

- name: Install Ntfy.sh
  ansible.builtin.apt:
    update_cache: yes
    name: ntfy
    state: present

- name: Enable service
  ansible.builtin.service:
    name: ntfy
    enabled: true
    state: started
