---
- name: Check if PiHole is installed
  ansible.builtin.command: |
    if command -v pihole; then
      echo 'present'
    else
      echo 'absent'
    fi
  register: pihole_status
  changed_when: pihole_status.rc != 0

- name: Install PiHole
  ansible.builtin.command: curl -sSL https://install.pi-hole.net | bash
  when: pihole_status == 'absent'
  changed_when: pihole_status.rc != 0

- name: Update PiHole
  ansible.builtin.command: pihole -u
  when: pihole_status == 'present'
  changed_when: pihole_status.rc == 0
