---
- name: Check if PiHole is installed
  block:
    - name: Check pihole command
      ansible.builtin.shell: |
        if command -v pihole; then
          echo 'present'
        else
          echo 'absent'
        fi
      register: pihole_status
    - name: Fail if PiHole not installed
      ansible.builtin.fail:
        msg: |
          Failing as PiHole not installed on host.
          Installation needs to be done manually due to nesesary interactive elements, stable headless method currently not available.
          Please install manually by running 'curl -sSL https://install.pi-hole.net | bash' on the host as root.
      when: pihole_status.stdout == 'absent'

- name: Update PiHole
  ansible.builtin.shell: pihole -up

- name: Install unbound DNS
  ansible.builtin.package:
    name: unbound
    state: present
  notify: Restart unbound

- name: Copy unbound config
  ansible.builtin.copy:
    src: pi-hole.conf
    dest: /etc/unbound/unbound.conf.d/pi-hole.conf
  notify: Restart unbound
