---
- name: Check if PiHole is installed
  ansible.builtin.shell: |
    if command -v pihole; then
      echo 'present'
    else
      echo 'absent'
    fi
  register: pihole_status

- name: DEBUG
  ansible.builtin.debug:
    msg: "{{ pihole_status }}"

- name: Install PiHole
  ansible.builtin.shell: curl -sSL https://install.pi-hole.net | bash
  when: pihole_status == 'absent'

- name: Update PiHole
  ansible.builtin.shell: pihole -u
  when: pihole_status == 'present'
