---
- name: Check if PiHole is installed
  ansible.builtin.shell: |
    if command -v pihole; then
      echo 'present'
    else
      echo 'absent'
    fi
  register: pihole_status

- name: Install PiHole
  block:
    - name: Get installer
      ansible.builtin.get_url: 
        url: https://install.pi-hole.net
        dest: /tmp/pihole-install.sh
    - name: Run installer
      ansible.builtin.shell: bash /tmp/pihole-install.sh  
  when: pihole_status.stdout == 'absent'

- name: Update PiHole
  ansible.builtin.shell: pihole -u
  when: pihole_status.stdout == 'present'
