---
- name: Check if PiHole is installed
  ansible.builtin.shell: command -v pihole
  register: pihole_status

- name: Install PiHole
  ansible.builtin.shell: curl -sSL https://install.pi-hole.net | bash
  when: pihole_status.rc != 0

- name: Update PiHole
  ansible.builtin.shell: pihole -u
  when: pihole_status.rc == 0
