---
- name: Install bind9
  ansible.builtin.apt:
    name:
      - bind9
      - bind9-utils
    state: present

- name: Bind9 log folder
  ansible.builtin.file:
    path: /var/log/bind
    state: directory
    owner: bind
    group: bind
  notify:
    - Restart bind9

- name: Bind9 comfig folder
  ansible.builtin.file:
    path: /etc/bind
    state: directory
    owner: bind
    group: bind
  notify:
    - Restart bind9

- name: Bind9 options
  ansible.builtin.copy:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
  notify:
    - Restart bind9

- name: Bind9 local
  ansible.builtin.copy:
    src: named.conf.local
    dest: /etc/bind/named.conf.local
  notify:
    - Restart bind9

- name: DNS Tsig Key
  ansible.builtin.template:
    src: tsig-key.key.j2
    dest: /etc/bind/tsig-key.key
  notify:
    - Restart bind9

- name: home.matagoth.com zone
  ansible.builtin.template:
    src: home-matagoth-com.zone.j2
    dest: /etc/bind/home-matagoth-com.zone
  notify:
    - Restart bind9
