---
- name: Keyrings folder
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory

- name: Instal gpg
  ansible.builtin.apt:
    name: gpg
    state: present

- name: Docker gpg key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/keyrings/docker.gpg

- name: Instal apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Docker repo
  ansible.builtin.copy:
    src: docker.list
    dest: /etc/apt/sources.list.d/docker.list

- name: Install Docker
  ansible.builtin.apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Enable tun module
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: tun
  notify:
    - Reboot
