---
version: "3.8"

services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /containers/homer/assets/:/www/assets
    ports:
      - 8080:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
