---
version: "3.8"

services:
  homer:
    restart: always
    image: b4bz/homer:v23.10.1
    container_name: homer
    volumes:
      - /containers/homer/assets/:/www/assets
    ports:
      - 8080:8080
    user: root:root
    environment:
      - INIT_ASSETS=1
