---
version: "3.8"

services:
  pontainer:
    restart: unless-stopped
    image: portainer/portainer-ce:2.19.4
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - pontainer_data:/data

volumes:
  pontainer_data:
