#!/bin/bash

docker run --rm \
  --name runner \
  -v /pve/terraform:/pve/terraform \
  -v /home/runner/.ssh:/root/.ssh \
  -v .:/build \
  -w /build \
  -e DNS_TSIG_KEY="${DNS_TSIG_KEY}" \
  runner-toolbox \
  "${@}"
