#!/bin/bash

# This script is used to run the github runner toolbox container

docker run --rm \
  --name runner \
  -v /pve/terraform:/pve/terraform \
  -v /pve/secrets:/pve/secrets \
  -v /home/runner/.ssh:/root/.ssh \
  -v .:/build \
  -w /build \
  runner-toolbox \
  "${@}"
