#!/bin/bash

docker run --rm \
  --name runner \
  -v /pve/terraform:/pve/terraform \
  -v .:/build \
  -w /build \
  -e PM_USER="${PM_USER}" \
  -e PM_PASS="${PM_PASS}" \
  runner-toolbox \
  "${@}"
