name: Build Runner Image

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - 'runner-toolbox/**'


jobs:
  BuildRunnerImage:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prune docker resources
        run: docker system prune -f
      - name: Build Image
        run: docker build runner-toolbox -t runner-toolbox:latest
  Ntfy:
    runs-on: self-hosted
    if: always() 
    needs:
      - BuildRunnerImage
    steps: 
      - name: Ntfy
        run: ./run/execute_runner ntfy_workflow_status '${{ github.workflow }}' '${{ needs.BuildRunnerImage.result }}' 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
