name: DNS

on:
  workflow_call:
    inputs:
      tf_action:
        type: string
        required: true
        description: terraform action
        default: plan
      skip_notify:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      tf_action:
        type: choice
        required: true
        description: terraform action
        default: plan
        options:
          - plan
          - apply
          - destroy_plan
          - destroy
      skip_notify:
        type: boolean
        required: false
        default: false
        description: skip notifications
  push:
    branches:
      - main
    paths:
      - 'terraform/dns/**'

concurrency: dns

jobs:
  RunDNS:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform
        run: ./run/execute_runner terraform_dns ${{ github.event_name == 'push' && 'apply' || inputs.tf_action }}
  Ntfy:
    runs-on: self-hosted
    if: ${{ always() && !inputs.skip_notify }}
    needs:
      - RunDNS
    steps: 
      - name: Ntfy
        run: ./run/execute_runner ntfy_workflow_status '${{ github.workflow }} - ${{ github.event_name == 'push' && 'apply' || inputs.tf_action }}' '${{ needs.RunDNS.result }}' 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
