name: DNS

on:
  workflow_call:
    inputs:
      tf_action:
        type: string
        required: true
        description: terraform action
        default: plan
  workflow_dispatch:
    inputs:
      tf_action:
        type: choice
        required: true
        description: terraform action
        default: plan
        options:
          - plan
          - apply
          - destroy_plan
          - destroy
  push:
    branches:
      - main
    paths:
      - 'terraform/dns/**'

concurrency: dns

env:
  DNS_TSIG_KEY: ${{ secrets.DNS_TSIG_KEY }}

jobs:
  RunDNS:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform
        run: ./run/execute_runner terraform_dns ${{ github.event_name == 'push' && 'apply' || inputs.tf_action }}
      - name: Ntfy
        if: always()
        run: ./run/execute_runner ntfy_workflow_status '${{ github.workflow }} - ${{ github.event_name == 'push' && 'apply' || inputs.tf_action }}' '${{ github.action_status }}' 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
