name: LXC

on:
  workflow_call:
    inputs:
      vmid:
        type: string
        required: true
        description: lxc id
      tf_action:
        type: string
        required: true
        description: terraform action
        default: plan
  workflow_dispatch:
    inputs:
      vmid:
        type: string
        required: true
        description: lxc id
      tf_action:
        type: choice
        required: true
        description: terraform action
        default: plan
        options:
          - plan
          - apply
          - plan_destroy
          - destroy

concurrency: lxc

env:
  PM_USER: ${{ secrets.PM_USER }}
  PM_PASS: ${{ secrets.PM_PASS }}
  DNS_TSIG_KEY: ${{ secrets.DNS_TSIG_KEY }}

jobs:
  RunLXC:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform
        run: ./run/execute_runner terraform_lxc ${{ inputs.vmid }} ${{ inputs.tf_action }}
      - name: Ansible
        if: ${{ inputs.tf_action == 'apply' }}
        run: ./run/execute_runner ansible_lxc ${{ inputs.vmid }}
