name: Build Runner Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'runner-toolbox/**'

concurrency: theres-only-one-runner

jobs:
  BuildRunnerImage:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Image
        run: |
          whoami
          pwd
          docker build ./runner-toolbox/ -t runner-toolbox
