name: Build Runner Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build_runner_image.yml'
      - 'runner-toolbox/**'

concurrency: theres-only-one-runner

jobs:
  BuildRunnerImage:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Image
        run: |
          DOCKER_BUILDKIT=1 docker build ./runner-toolbox/ -t runner-toolbox
