name: HomeLab IAC

on:
  workflow_dispatch:
    inputs:
      tf_action:
        type: choice
        required: true
        description: terraform action
        default: plan
        options:
          - plan
          - apply
          - destroy_plan
          - destroy
      skip_notify:
        type: boolean
        required: false
        description: skip notifications
        default: false

concurrency: homelab-iac

jobs:
  BuildRunnerImage:
    uses: ./.github/workflows/_build_runner_image.yml
    with:
      skip_notify: ${{ inputs.skip_notify || false }}
  DeployLXCs:
    needs:
      - BuildRunnerImage
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        vmid:
          - 100   # pihole + unbound
          - 110   # reverse proxy
          - 201   # bind9
          - 202   # ntfy
          - 203   # fileserver
          - 204   # jellyfin
          - 205   # docker host
          - 206   # home assistant
          - 207   # local AI
          - 208   # CloudFlare tunnel worker
          - 209   # Signum miner
          - 210   # Prometheus & Grafana
          - 211   # n8n
          - 212   # mosquitto
          - 213   # NetAlertX
          - 215   # NetBox
    uses: ./.github/workflows/_lxc.yml
    secrets: inherit
    with:
      vmid: ${{ matrix.vmid }}
      tf_action: ${{ inputs.tf_action || 'apply' }}
      skip_notify: ${{ inputs.skip_notify || false}}
  DeployVMs:
    needs:
      - BuildRunnerImage
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        vmid:
          - 214   # vm-01 (general-purpose, currently switchbot BLE bridge)
    uses: ./.github/workflows/_vm.yml
    secrets: inherit
    with:
      vmid: ${{ matrix.vmid }}
      tf_action: ${{ inputs.tf_action || 'apply' }}
      skip_notify: ${{ inputs.skip_notify || false}}
  DeployExternalHosts:
    needs:
      - BuildRunnerImage
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        hostname:
          - pi-01   # general-purpose RPi (GPIO)
    uses: ./.github/workflows/_external_host.yml
    secrets: inherit
    with:
      hostname: ${{ matrix.hostname }}
      skip_notify: ${{ inputs.skip_notify || false }}
  UpdateDNSRecords:
    needs:
      - BuildRunnerImage
    name: Update DNS records
    uses: ./.github/workflows/_dns.yml
    with:
      tf_action: ${{ inputs.tf_action || 'apply' }}
      skip_notify: ${{ inputs.skip_notify || false }}
