name: HomeLab IAC

on:
  workflow_dispatch:
    inputs:
      tf_action:
        type: choice
        required: true
        description: terraform action
        default: plan
        options:
          - plan
          - apply
          - destroy_plan
          - destroy
      skip_notify:
        type: boolean
        required: false
        description: skip notifications
        default: false
  # push:
  #   branches:
  #     - main

concurrency: homelab-iac

jobs:
  BuildRunnerImage:
    uses: ./.github/workflows/_build_runner_image.yml
    with:
      skip_notify: ${{ inputs.skip_notify }}
  DeployLXCs:
    needs:
      - BuildRunnerImage
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        vmid:
          - 100   # pihole + unbound
          - 201   # bind9
          - 202   # ntfy
          - 203   # fileserver
          - 204   # jellyfin
          - 205   # docker host
          - 207   # local AI
          - 208   # CloudFlare tunnel worker
          - 209   # Signum miner
    uses: ./.github/workflows/_lxc.yml
    secrets: inherit
    with:
      vmid: ${{ matrix.vmid }}
      tf_action: ${{ inputs.tf_action }}
      skip_notify: ${{ inputs.skip_notify }}
  UpdateDNSRecords:
    needs:
      - BuildRunnerImage
    name: Update DNS records
    uses: ./.github/workflows/_dns.yml
    with:
      tf_action: ${{ inputs.tf_action }}
      skip_notify: ${{ inputs.skip_notify }}
