name: Lint

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build runner-toolbox image (cached)
        run: docker build runner-toolbox -t runner-toolbox:latest
      - name: Run linters
        run: ./run/lint
